fix(selenium-webdriver): Fix clear() and sendKeys() return type
Since https://github.com/angular/protractor/pull/896 (protractor
Since commit 3c0e727 of protractor (see PR angular/protractor#896), it
is allowed to chain actions (i.e.
`element(By.x).clear().sendKeys('abc)`).

------------------------------------------------------------
| Ah ben non car en fait, selenium-webdriver != protractor |
------------------------------------------------------------

Since then, the return type of
clear() and sendKeys() is not longer a Promise<void>, but the WebElement
itself.

This commit fixes the docs.

It will allow typings for selenium-webdriver to be corrected. Until now, TypeScript complains with:

error TS2339: Property 'sendKeys' does not exist on type 'Promise<void>'.